### ISSUE TITLE
Change flashable.zip to be more self descriptive

### ISSUE THREAD

**Issue by McLoo** [dosomder/PRFCreator#2]
What I have in in mind is something like

``` CS
File.Move("flashable.zip", Path.GetFileNameWithoutExtension(form.ftf_textbox.Text) + "_flashable_prerooted.zip")
```

I'm pretty sure two weeks after creating a flashable.zip I don't know what's inside :)

**Comment by dosomder** [comment]
Thanks for your suggestion. I will consider to implement it in the next version

**Comment by dosomder** [comment]
With the latest commit you can also specify the destination file yourself. I consider this issue as solved so I'm closing it. If you still have something to add, feel free to reopen it.
