### ISSUE TITLE
Not working on MTK Devices (C4)

### ISSUE THREAD

**Issue by eoinkennedy** [dosomder/PRFCreator#4]
Hi,
Created a flashable zip for my C4.
Into Recovery I went, and chose to flash the file.

Get this error:
Error: UUID link to system partition does not exist

Checking the code in updater-script-uuid, line 33-39, I can see this :

if
run_program("/tmp/busybox", "ls", "/dev/block/platform/msm_sdcc.1/by-uuid/SYSTEMUUID") != "0"
then
abort("Error: UUID link to system partition does not exist");
endif;
assert(package_extract_file("system.ext4", "/dev/block/platform/msm_sdcc.1/by-uuid/SYSTEMUUID"));
set_progress(0.550000);

But my device has 
/dev/block/platform/mtk.msdc.0 directory, 
no msm_sdcc.1 directory.

A few of the shell scripts have the same issue, using /msm_sdcc.1 directory.

E

**Comment by dosomder** [comment]
Thanks for your report. Please let me know which version of PRFCreator you used and what options you selected.

**Comment by eoinkennedy** [comment]
Hi,

I'm using version 1.1.0.0

Options I have ticked on are
   Kernel
   FOTAKernel
   Modem
   LTALabel
   Legacy mode

Get error messages 
    Could not find amss_fsg/fs_1/fs_2

Zip file is created, but not flashable.

![prfcreator](https://cloud.githubusercontent.com/assets/16816811/12507103/69dee69c-c0eb-11e5-9ba4-512ddbe90649.png)

**Comment by dosomder** [comment]
I will look into it. Why are you using Legacy Mode? It currently won't work either without Legacy Mode but I'm just interested.

**Comment by eoinkennedy** [comment]
Hi,
I get an error message when not using Legacy Mode.
![prfcreator 2](https://cloud.githubusercontent.com/assets/16816811/12508971/194708d4-c0f7-11e5-86de-c3ddf28758ef.png)

Thanks.

**Comment by eoinkennedy** [comment]
FTF file was created using, Xperifirm and Flashtool (v0.9.19.8), as detailed here:
http://www.xperiablog.net/2014/08/16/create-your-own-ftf-firmware-files-using-xperifirm-and-flashtool-guide/

In the ftf file, there is a "partitions.sin" file, but no "partition-image.sin" file.

**Comment by dosomder** [comment]
Please provide me the following:
- List the contents of FTF file (screenshot)
- List the files located in `/dev/block`
- List the folders located in `/dev/block/platform`

Thanks for your help

**Comment by eoinkennedy** [comment]
![prfcreator 3](https://cloud.githubusercontent.com/assets/16816811/12510941/859221aa-c105-11e5-80b3-9ebafda33c49.png)
![prfcreator 4](https://cloud.githubusercontent.com/assets/16816811/12510946/8b73b9c6-c105-11e5-980d-cc8bf8aa8b9c.png)

[devblock.txt](https://github.com/dosomder/PRFCreator/files/100829/devblock.txt)
[devblockpatform.txt](https://github.com/dosomder/PRFCreator/files/100830/devblockpatform.txt)

**Comment by dosomder** [comment]
Could you try with this version and **not** using Legacy Mode?
[PRFTest.zip](https://github.com/dosomder/PRFCreator/files/101095/PRFTest.zip)

**Comment by eoinkennedy** [comment]
Created new zip file without Legacy Mode, and flashed.

Got two errors
    Error flashing ltalabel.sin
    Error flashing fotakernel.sin

And phone would not restart. :(

I'll try again with a few TWRP tricks.

**Comment by dosomder** [comment]
Please provide the recovery log from after flashing

Edit: Looking into the issue

**Comment by dosomder** [comment]
Try using the following test version
[PRFTest.zip](https://github.com/dosomder/PRFCreator/files/101474/PRFTest.zip)

**Comment by eoinkennedy** [comment]
Hi,
This newest version you have posted works perfectly.
Fully rooted Xperia C4 with Stock android 5.1.

Thank you so much

**Comment by dosomder** [comment]
Thank you a lot for testing and reporting the issue!

**Comment by dosomder** [comment]
This issue is fixed in the v1.2 release.
